import pandas as pd
import matplotlib.pyplot as plt

# --- CONFIGURATION ---
# Paths to the CSV logs generated by train.py and evaluate.py
training_log_path = 'D:/University/Junior/DL/Brain_Tumor_Segmentation/logs/run_20251210-022434/training_log.csv'
final_scores_path = 'D:/University/Junior/DL/Brain_Tumor_Segmentation/logs/run_20251210-022434/final_scores.csv'

# 1. Load the data
training_data = pd.read_csv(training_log_path)
final_scores_data = pd.read_csv(final_scores_path)

# 2. Process final scores data
# Filter out summary rows if present
patient_data = final_scores_data[final_scores_data['PatientID'] != 'Final_Result_Average'].copy()
metrics = ['WT', 'TC', 'ET']
for metric in metrics:
    patient_data[metric] = pd.to_numeric(patient_data[metric])

# 3. Create a Grid Layout for the Plots
fig = plt.figure(figsize=(14, 10))

# --- Top Plot: Training vs Validation Loss ---
ax1 = plt.subplot(2, 1, 1)
ax1.plot(training_data['Epoch'], training_data['Train Loss'], label='Train Loss', color='blue', alpha=0.7)
ax1.plot(training_data['Epoch'], training_data['Val Loss'], label='Val Loss', color='orange', alpha=0.7)

# Highlight epochs where the best model was saved
best_model_epochs = training_data[training_data['Best Model Saved'] == 'Yes']
ax1.scatter(best_model_epochs['Epoch'], best_model_epochs['Val Loss'], 
            color='red', marker='*', s=120, label='Best Model Saved', zorder=5)

ax1.set_title('Training Progress: Loss over Epochs')
ax1.set_ylabel('Loss')
ax1.set_xlabel('Epoch')
ax1.legend()
ax1.grid(True, linestyle='--', alpha=0.6)

# --- Bottom Left Plot: Box Plot of Scores ---
# Shows the distribution and outliers for WT, TC, and ET scores.
ax2 = plt.subplot(2, 2, 3)
patient_data.boxplot(column=metrics, ax=ax2, grid=True)
ax2.set_title('Final Evaluation: Score Distribution')
ax2.set_ylabel('Dice Score')
ax2.set_ylim(0, 1.05)

# --- Bottom Right Plot: Histogram of Scores ---
# Shows the frequency distribution of Dice scores across the validation set.
ax3 = plt.subplot(2, 2, 4)
for metric in metrics:
    ax3.hist(patient_data[metric], bins=20, alpha=0.5, label=metric)

ax3.set_title('Final Evaluation: Score Frequency')
ax3.set_xlabel('Dice Score')
ax3.set_ylabel('Number of Patients')
ax3.legend(loc='upper left')
ax3.grid(True, linestyle='--', alpha=0.5)

# Adjust layout to prevent overlapping
plt.tight_layout()
plt.show()